FROM hypriot/rpi-alpine
#FROM resin/raspberrypi3-alpine:3.6

MAINTAINER David Coppit <david@coppit.org>

ENV TERM=xterm-256color

RUN true && \
\
echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/community" >> /etc/apk/repositories && \
apk --update upgrade && \
\
# Basics, including runit
apk add bash curl htop runit && \
\
# Needed by our code
apk add expect libc6-compat && \
\
# Alpine Build Tools
apk add alpine-sdk && \
\
rm -rf /var/cache/apk/*

ADD https://www.noip.com/client/linux/noip-duc-linux.tar.gz /files/

RUN set -x && \
  chmod a+rwX /files && \
  tar -C /files -x -f /files/noip-duc-linux.tar.gz && \
  make -C /files/noip-2.1.9-1 && \
  cp /files/noip-2.1.9-1/noip2 /usr/local/bin/noip2
